# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tc6xgYpdMXVlUtsWF6_bAlpFA_R2daOX
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Fano 2-22 Predicts the Fine-Structure Constant
High-Precision Version using mpmath (50 decimal digits)

Author: Massimiliano Blandino
Concept DOIs: 10.5281/zenodo.19802606 (Alpha Series)
              10.5281/zenodo.19955544 (Fano Series)
"""

import mpmath as mp
import numpy as np
import matplotlib.pyplot as plt

# Set precision to 50 decimal digits
mp.dps = 50

# ============================================================================
# 1. PURE STRUCTURAL PARAMETERS (GEOMETRIC INPUTS - NO FITTING)
# ============================================================================
D = 45                                # Bond dimension = dim(adj SO(10))
T = mp.mpf(8)                         # String tension (√T = 2√2)
PHASE = mp.pi / 6                     # Topological phase from hinge term
DIM_H_FANO = 105                      # dim(adj SO(15)) = 105
B_EM_SM = mp.mpf(4.1)                 # Standard Model beta coefficient at M_Z
M_Z = mp.mpf(91.1876)                 # Z boson mass (GeV)
M_PLANCK = mp.mpf(1.2209e19)          # Planck mass (GeV)

# ============================================================================
# 2. ALGEBRAIC DERIVATIONS (HIGH PRECISION)
# ============================================================================

def calculate_entanglement():
    """S = 2√(1 + sin²(2θ)) with θ = π/6 → √7"""
    sin_2theta = mp.sin(2 * PHASE)
    return 2 * mp.sqrt(1 + sin_2theta**2)

def calculate_deficit(s_realized):
    """ΔS = √8 - √7"""
    s_max = mp.sqrt(T)
    return s_max - s_realized

def calculate_alpha_gut_inv(s_realized):
    """α_GUT^{-1} = dim(H_Fano) / entanglement eigenvalue = 105/√7 = 15√7"""
    return DIM_H_FANO / s_realized

def calculate_m_gut(delta_s):
    """M_GUT = M_Pl · ΔS"""
    return M_PLANCK * delta_s

def calculate_threshold_correction(s_max, delta_s):
    """δ_th = (1/2π) ln(√8 / ΔS)"""
    return (1 / (2 * mp.pi)) * mp.log(s_max / delta_s)

def calculate_delta_b_geom():
    """Δb_geom = dim(SO(15)) / dim(SO(5)) = 105 / 10 = 10.5"""
    dim_SO5_adj = 10
    return mp.mpf(DIM_H_FANO) / dim_SO5_adj

def calculate_delta_b_bound(delta_s):
    """Δb_bound = ΔS / (2π)"""
    return delta_s / (2 * mp.pi)

def calculate_b_em_eff(b_sm, delta_b_geom, delta_b_bound):
    """b_EM^eff = b_EM^SM + Δb_geom + Δb_bound"""
    return b_sm + delta_b_geom + delta_b_bound

def calculate_alpha_em_inv(alpha_gut_inv, b_em_eff, log_ratio, delta_th):
    """Solve RGE for alpha_EM^{-1}(M_Z)"""
    return alpha_gut_inv + (b_em_eff / (2 * mp.pi)) * log_ratio + delta_th

# ============================================================================
# 3. MAIN VERIFICATION
# ============================================================================

def run_verification():
    print("=" * 70)
    print("FANO 2-22 PREDICTS THE FINE-STRUCTURE CONSTANT")
    print("=" * 70)
    print(f"mpmath precision: {mp.dps} decimal digits\n")
    print("No free parameters. All quantities derived from topology.\n")

    # Step 1: Entanglement from hinge term
    s_realized = calculate_entanglement()
    s_max = mp.sqrt(T)
    delta_s = calculate_deficit(s_realized)

    # Step 2: GUT parameters
    alpha_gut_inv = calculate_alpha_gut_inv(s_realized)
    m_gut = calculate_m_gut(delta_s)
    log_ratio = mp.log(m_gut / M_Z)

    # Step 3: Threshold correction (Picard-Fuchs)
    delta_th = calculate_threshold_correction(s_max, delta_s)

    # Step 4: Beta coefficient deviations
    delta_b_geom = calculate_delta_b_geom()
    delta_b_bound = calculate_delta_b_bound(delta_s)
    b_em_eff = calculate_b_em_eff(B_EM_SM, delta_b_geom, delta_b_bound)

    # Step 5: Prediction of alpha_EM^{-1}(M_Z)
    alpha_em_inv_pred = calculate_alpha_em_inv(alpha_gut_inv, b_em_eff, log_ratio, delta_th)

    # Step 6: Experimental value (CODATA 2022)
    alpha_em_inv_exp = mp.mpf(127.955)
    diff = alpha_em_inv_pred - alpha_em_inv_exp
    rel_error = diff / alpha_em_inv_exp * 100

    # Convert to float for printing (CRITICAL: mpf cannot be formatted directly)
    sqrt_T_val = float(mp.sqrt(T))
    phase_val = float(PHASE)
    s_realized_val = float(s_realized)
    sqrt7_val = float(mp.sqrt(7))
    delta_s_val = float(delta_s)
    alpha_gut_inv_val = float(alpha_gut_inv)
    fifteen_sqrt7_val = float(15 * mp.sqrt(7))
    m_gut_val = float(m_gut)
    log_ratio_val = float(log_ratio)
    delta_th_val = float(delta_th)
    delta_b_geom_val = float(delta_b_geom)
    delta_b_bound_val = float(delta_b_bound)
    b_em_eff_val = float(b_em_eff)
    alpha_em_inv_pred_val = float(alpha_em_inv_pred)
    alpha_em_inv_exp_val = float(alpha_em_inv_exp)
    diff_val = float(diff)
    rel_error_val = float(rel_error)
    b_em_sm_val = float(B_EM_SM)

    # Output
    print("--- PURE STRUCTURAL PARAMETERS ---")
    print(f"Bond dimension D                      = {D} = dim(adj SO(10))")
    print(f"String tension T                      = {T} (√T = 2√2 = {sqrt_T_val:.15f})")
    print(f"Topological phase θ                   = π/6 = {phase_val:.10f}")
    print(f"Fano Hilbert space dim                = {DIM_H_FANO} = dim(adj SO(15))")
    print()

    print("--- DERIVED FROM TOPOLOGY ---")
    print(f"1. Realized entanglement S:           {s_realized_val:.20f}")
    print(f"   (Check: √7 = {sqrt7_val:.20f})")
    print(f"2. Entanglement deficit ΔS:           {delta_s_val:.20f}")
    print(f"3. Bare GUT coupling α_GUT⁻¹:         {alpha_gut_inv_val:.20f} (15√7 = {fifteen_sqrt7_val:.20f})")
    print(f"4. Unification scale M_GUT:           {m_gut_val:.4e} GeV")
    print(f"5. Log ratio ln(M_GUT/M_Z):           {log_ratio_val:.10f}")
    print(f"6. Threshold correction δ_th:         {delta_th_val:.12f}")
    print()

    print("--- BETA COEFFICIENT (FROM BRANCHING DECOMPOSITION) ---")
    print(f"7. Δb_geom = dim(SO(15))/dim(SO(5)) = {DIM_H_FANO}/10 = {delta_b_geom_val}")
    print(f"8. Δb_bound = ΔS/(2π) = {delta_s_val:.10f}/(2π) = {delta_b_bound_val:.10f}")
    print(f"9. b_EM^SM (Standard Model, M_Z) :    {b_em_sm_val}")
    print(f"10. b_EM^eff = {b_em_sm_val} + {delta_b_geom_val} + {delta_b_bound_val:.8f} = {b_em_eff_val:.12f}")
    print()

    print("--- PREDICTION vs EXPERIMENT ---")
    print(f"Predicted α_EM⁻¹(M_Z):                {alpha_em_inv_pred_val:.12f}")
    print(f"Experimental α_EM⁻¹(M_Z) (CODATA):    {alpha_em_inv_exp_val:.12f}")
    print(f"Difference:                           {diff_val:.12f} ({rel_error_val:.5f}%)")
    print()

    print("=" * 70)
    print("VERIFICATION COMPLETE. NO FREE PARAMETERS.")
    print("The Fano 2-22 predicts the fine-structure constant.")
    print("=" * 70)

    return {
        's_realized': s_realized_val,
        'delta_s': delta_s_val,
        'alpha_gut_inv': alpha_gut_inv_val,
        'm_gut': m_gut_val,
        'delta_th': delta_th_val,
        'delta_b_geom': delta_b_geom_val,
        'delta_b_bound': delta_b_bound_val,
        'b_em_eff': b_em_eff_val,
        'alpha_em_inv_pred': alpha_em_inv_pred_val,
        'alpha_em_inv_exp': alpha_em_inv_exp_val,
        'log_ratio': log_ratio_val
    }

# ============================================================================
# 4. PLOTS
# ============================================================================

def generate_plots(results):
    """Generate verification plots"""

    alpha_pred = results['alpha_em_inv_pred']
    alpha_exp = results['alpha_em_inv_exp']
    delta_b_geom = results['delta_b_geom']
    delta_b_bound = results['delta_b_bound']
    b_sm = 4.1
    b_eff = results['b_em_eff']

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    # Bar chart: Prediction vs Experiment
    labels = ['Predicted', 'Experimental']
    values = [alpha_pred, alpha_exp]
    colors = ['#2E86AB', '#A23B72']
    bars = ax1.bar(labels, values, color=colors, edgecolor='black', linewidth=1.5)
    ax1.axhline(y=alpha_exp, color='gray', linestyle='--', alpha=0.5)
    ax1.set_ylabel(r'$\alpha_{\mathrm{EM}}^{-1}(M_Z)$')
    ax1.set_title('Fano 2-22 Prediction vs Experiment')
    ax1.text(0, alpha_pred + 0.3, f'{alpha_pred:.3f}', ha='center', fontsize=10)
    ax1.text(1, alpha_exp + 0.3, f'{alpha_exp:.3f}', ha='center', fontsize=10)
    ax1.grid(True, alpha=0.3)

    # Pie chart: Contributions to b_EM^eff
    contributions = [b_sm, delta_b_geom, delta_b_bound]
    contribution_labels = [
        f'Standard Model\n{b_sm:.1f}',
        f'SO(15)/SO(5) Branching\n{delta_b_geom:.1f}',
        f'Boundary (ΔS/2π)\n{delta_b_bound:.5f}'
    ]
    colors_pie = ['#2E86AB', '#F18F01', '#C73E1D']
    ax2.pie(contributions, labels=contribution_labels, colors=colors_pie,
            autopct='%1.1f%%', startangle=90, explode=(0.05, 0.05, 0.1))
    ax2.set_title(r'Contributions to $b_{\mathrm{EM}}^{\mathrm{eff}}$')

    plt.tight_layout()
    plt.savefig('fano2_22_alpha_prediction.png', dpi=150, bbox_inches='tight')
    plt.show()

    # Figure 2: Beta coefficient contributions (stacked bar)
    fig2, ax3 = plt.subplots(figsize=(8, 5))

    widths = [b_sm, delta_b_geom, delta_b_bound]
    colors_stack = ['#2E86AB', '#F18F01', '#C73E1D']
    labels_stack = ['Standard Model', 'SO(15)/SO(5)', 'Boundary (ΔS/2π)']

    bottom = 0
    for i, (w, color, label) in enumerate(zip(widths, colors_stack, labels_stack)):
        ax3.bar(0, w, bottom=bottom, color=color, edgecolor='black',
                linewidth=1, label=label)
        bottom += w

    ax3.set_xticks([0])
    ax3.set_xticklabels([r'$b_{\mathrm{EM}}^{\mathrm{eff}}$'])
    ax3.set_ylabel(r'$b_{\mathrm{EM}}$')
    ax3.set_title(f'Total $b_{{\\mathrm{{EM}}}}^{{\\mathrm{{eff}}}} = {b_eff:.3f}$')
    ax3.legend(loc='upper left')
    ax3.grid(True, alpha=0.3, axis='y')

    plt.tight_layout()
    plt.savefig('fano2_22_beta_contributions.png', dpi=150, bbox_inches='tight')
    plt.show()

    print("\n--- PLOTS SAVED ---")
    print("Figure 1: fano2_22_alpha_prediction.png")
    print("Figure 2: fano2_22_beta_contributions.png")


def generate_sensitivity_plots(results):
    """Generate sensitivity plots for the prediction"""

    alpha_gut_inv = results['alpha_gut_inv']
    delta_th = results['delta_th']
    log_ratio = results['log_ratio']
    b_em_nominal = results['b_em_eff']
    alpha_exp = results['alpha_em_inv_exp']

    # Range for b_EM variation (±10%)
    b_range = np.linspace(b_em_nominal * 0.95, b_em_nominal * 1.05, 100)
    alpha_pred_range = [alpha_gut_inv + (b / (2 * np.pi)) * log_ratio + delta_th for b in b_range]

    # Range for log ratio variation (±5%)
    log_range = np.linspace(log_ratio * 0.95, log_ratio * 1.05, 100)
    alpha_pred_log = [alpha_gut_inv + (b_em_nominal / (2 * np.pi)) * log_r + delta_th for log_r in log_range]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    # Sensitivity to b_EM
    ax1.plot(b_range, alpha_pred_range, 'b-', linewidth=2)
    ax1.axhline(y=alpha_exp, color='r', linestyle='--', label=f'Experimental {alpha_exp:.3f}')
    ax1.axvline(x=b_em_nominal, color='gray', linestyle=':', alpha=0.5)
    ax1.set_xlabel(r'$b_{\mathrm{EM}}^{\mathrm{eff}}$')
    ax1.set_ylabel(r'Predicted $\alpha_{\mathrm{EM}}^{-1}(M_Z)$')
    ax1.set_title('Sensitivity: Prediction vs b_EM')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # Sensitivity to ln(M_GUT/M_Z)
    ax2.plot(log_range, alpha_pred_log, 'g-', linewidth=2)
    ax2.axhline(y=alpha_exp, color='r', linestyle='--', label=f'Experimental {alpha_exp:.3f}')
    ax2.axvline(x=log_ratio, color='gray', linestyle=':', alpha=0.5)
    ax2.set_xlabel(r'$\ln(M_{\mathrm{GUT}}/M_Z)$')
    ax2.set_ylabel(r'Predicted $\alpha_{\mathrm{EM}}^{-1}(M_Z)$')
    ax2.set_title('Sensitivity: Prediction vs Log Ratio')
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('fano2_22_sensitivity.png', dpi=150, bbox_inches='tight')
    plt.show()

    print("Figure 3: fano2_22_sensitivity.png")

# ============================================================================
# 5. MAIN EXECUTION
# ============================================================================

if __name__ == "__main__":
    results = run_verification()
    generate_plots(results)
    generate_sensitivity_plots(results)