# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tc6xgYpdMXVlUtsWF6_bAlpFA_R2daOX
"""

# ============================================================================
# Unified 5D Lagrangian – boundary vs bulk limits
# Author: Massimiliano Blandino
# ORCID: 0009-0006-3252-4011
# Supplementary material for:
# "Derivation of the Cosmological Constant from the 5D Lagrangian"
# ============================================================================

import numpy as np
import matplotlib.pyplot as plt

# ============================================================================
# Geometric and topological constants (no experimental input)
# ============================================================================
pi = np.pi
sqrt7 = np.sqrt(7)

# Geometric action of the oscillating circle (Chapter 3)
A = 4*pi**3 + pi**2 + pi

# Mean value of K^{-1} from the spectral model (Chapter 2)
K_inv_mean = 9.9327912864

# ============================================================================
# Unified Lagrangian with switch b
# b = 0 → boundary (alpha^-1, matter, electromagnetism)
# b = 1 → bulk (ln Lambda, vacuum, gravity)
# ============================================================================
def unified_action(b):
    if b == 0:
        # Boundary limit: fine-structure constant
        return A - 1/(24*A) - 1/(A**2 * pi**2 * K_inv_mean)
    elif b == 1:
        # Bulk limit: cosmological constant
        return -2*A - pi - sqrt7
    else:
        raise ValueError("b must be 0 (boundary) or 1 (bulk)")

# ============================================================================
# Compute both values
# ============================================================================
alpha_inv = unified_action(0)
ln_Lambda = unified_action(1)

# ============================================================================
# Tabular output
# ============================================================================
print("="*60)
print("UNIFIED 5D ACTION – BOUNDARY vs BULK")
print("="*60)
print(f"Geometric action A = {A:.12f}")
print(f"⟨K⁻¹⟩ = {K_inv_mean:.10f}")
print(f"√7 = {sqrt7:.10f}")
print("-"*60)
print(f"α⁻¹ (b=0, boundary) = {alpha_inv:.12f}")
print(f"ln Λ (b=1, bulk)    = {ln_Lambda:.12f}")
print("-"*60)

# ============================================================================
# Comparison with reference values (verification only, not used in calculation)
# ============================================================================
alpha_inv_CODATA = 137.035999177
ln_Lambda_Planck = -279.854817

diff_alpha = alpha_inv - alpha_inv_CODATA
diff_Lambda = ln_Lambda - ln_Lambda_Planck

print("Comparison with reference values (not used in calculation):")
print(f"α⁻¹ difference to CODATA 2022: {diff_alpha:.2e}")
print(f"ln Λ difference to Planck 2018: {diff_Lambda:.2e} (within 1.4% observational uncertainty)")
print("="*60)

# ============================================================================
# Plot: the two limits of the unified Lagrangian
# ============================================================================
b_vals = np.linspace(-0.2, 1.2, 100)
action_vals = np.array([unified_action(0) if b < 0.5 else unified_action(1) for b in b_vals])

plt.figure(figsize=(10, 6))
plt.step([-0.2, 0.5, 0.5, 1.2],
         [unified_action(0), unified_action(0), unified_action(1), unified_action(1)],
         where='mid', linewidth=2, color='blue', label='Unified action S_eff(b)')

plt.scatter([0], [alpha_inv], color='red', s=100, zorder=5, label='Boundary (α⁻¹)')
plt.scatter([1], [ln_Lambda], color='green', s=100, zorder=5, label='Bulk (ln Λ)')

plt.xlabel('Projection parameter b (0 = boundary, 1 = bulk)', fontsize=12)
plt.ylabel('Effective action S_eff(b)', fontsize=12)
plt.title('Unified 5D Lagrangian: boundary vs bulk limits', fontsize=14)
plt.grid(True, alpha=0.3)
plt.legend()
plt.tight_layout()
plt.savefig('unified_action_limits.png', dpi=150)
plt.show()

# ============================================================================
# Note on supplementary material
# ============================================================================
print("\nNote: This code is part of the supplementary material.")
print("The unified action is defined analytically; no experimental input is used.")
print("The figure 'unified_action_limits.png' is saved in the current directory.")