# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tc6xgYpdMXVlUtsWF6_bAlpFA_R2daOX
"""

# -*- coding: utf-8 -*-
"""
Quantum Alpha Structure Operator - Monolithic Verification with Graphics
Author: Massimiliano Blandino
ORCID: https://orcid.org/0009-0006-3252-4011
Date: April 2026

Description:
    Implements the quantum model of the fine-structure constant as an
    expectation value over a Hilbert space of bounded continued fractions.
    Five structural seals are incorporated:
    [1] Independence axiom (orthogonal draws per depth)
    [2] CODATA values as ensemble averages (ergodic convergence)
    [3] Postulate of {4,1,1}: A(x)=4x³+x²+x (empirical seed)
    [4] Dimensionless structure operator (not a physical Hamiltonian)
    [5] Subtractive chirality: K = 10 - F (stability anchoring)

Dependencies:
    numpy, mpmath, matplotlib

Precision: 200 decimal digits
Iterations: 1,000,000
Depth: 20
"""

import numpy as np
from mpmath import mp
import time
from collections import Counter
import matplotlib.pyplot as plt

# =================================================================================
# MODULE 1: ABSOLUTE PRECISION (200 decimal digits)
# =================================================================================
mp.dps = 200

# =================================================================================
# MODULE 2: POSTULATE OF {4,1,1} - The empirical seed
# =================================================================================
pi_mp = mp.pi

def A(x):
    """Postulate: A(x) = 4x^3 + x^2 + x"""
    return 4*x**3 + x**2 + x

A_pi = A(pi_mp)
A_third_derivative = mp.mpf(24)  # A'''(x) = 24 exactly

zero_order_term = A_pi
curvature_correction = 1 / (A_third_derivative * A_pi)
const_factor = 1 / (A_pi**2 * pi_mp**2)

codata_2022 = mp.mpf("137.035999177")

# =================================================================================
# MODULE 3: DISCRETE STATE SPACE AXIOM (Seal 1)
# q ∈ {1,...,45}, P(q) ∝ exp(-q/(2E_int)) with E_int = 5.0
# =================================================================================
max_q = 45
E_int = mp.mpf("5.0")

# Build probability distribution: P(q) ∝ exp(-q/10) because 2*E_int = 10
q_values_mp = [mp.mpf(str(q)) for q in range(1, max_q + 1)]
weights = [mp.exp(-q / (2 * E_int)) for q in q_values_mp]
total_weight = sum(weights)
probabilities = [float(w / total_weight) for w in weights]
q_space = np.arange(1, max_q + 1, dtype=np.int64)

# =================================================================================
# MODULE 4: QUANTUM ENGINE - SUBTRACTIVE CHIRALITY (Seal 5)
# Depth = 20, independent draws per depth (orthogonal degrees of freedom)
# =================================================================================
depth = 20
n_iterations = 1_000_000

def compute_structure_value(sequence):
    """
    Compute S = A(π) - 1/(24A(π)) - 1/(A(π)²π² K)
    with K = 10 - F, where F is the continued fraction of the sequence.
    This is the dimensionless structure operator (Seal 4).
    """
    # Reconstruct F from the bottom up (backwards recurrence)
    f = mp.mpf(str(sequence[-1]))
    for q in reversed(sequence[:-1]):
        f = mp.mpf(str(q)) + 1 / f
    f = 1 / f

    # Subtractive chirality: K = 10 - F (Seal 5)
    K = mp.mpf(10) - f

    # Quantum term
    quantum_term = const_factor / K

    # Dimensionless structure operator (Seal 4)
    S = zero_order_term - curvature_correction - quantum_term

    return float(S)

print("=" * 80)
print("QUANTUM ALPHA STRUCTURE OPERATOR - MONOLITHIC VERIFICATION")
print("=" * 80)
print(f"Precision: {mp.dps} decimal digits")
print(f"Iterations: {n_iterations:,}")
print(f"Depth: {depth}")
print(f"q-space: 1 to {max_q}")
print(f"E_int = 5.0 (P(q) ∝ exp(-q/10))")
print("-" * 80)
print("SEALS INCORPORATED:")
print("  [1] Independence axiom: orthogonal draws per depth")
print("  [2] CODATA values as ensemble averages (ergodic convergence)")
print("  [3] Postulate of {4,1,1}: A(x)=4x³+x²+x (empirical seed)")
print("  [4] Dimensionless structure operator (not a physical Hamiltonian)")
print("  [5] Subtractive chirality: K = 10 - F (stability anchoring)")
print("=" * 80)
print()

# =================================================================================
# RUN SIMULATION
# =================================================================================
start_time = time.time()

S_values = []
all_sequences = []  # Store for graphics
sequence = np.zeros(depth, dtype=np.int64)

for i in range(n_iterations):
    # Generate independent draws for each depth (Seal 1)
    for j in range(depth):
        sequence[j] = np.random.choice(q_space, p=probabilities)

    S = compute_structure_value(sequence)
    S_values.append(S)
    all_sequences.append(sequence.copy())

    if (i + 1) % 100_000 == 0:
        elapsed = time.time() - start_time
        print(f"  Progress: {i+1:,}/{n_iterations:,} | Time: {elapsed:.1f}s")

elapsed_total = time.time() - start_time

# =================================================================================
# RESULTS
# =================================================================================
S_array = np.array(S_values)
mean_S = np.mean(S_array)
std_S = np.std(S_array)
min_S = np.min(S_array)
max_S = np.max(S_array)

print()
print("=" * 80)
print("RESULTS")
print("=" * 80)
print(f"Total time: {elapsed_total:.2f} seconds")
print(f"Mean ⟨S⟩ (predicted α⁻¹): {mean_S:.12f}")
print(f"Standard deviation: {std_S:.2e}")
print(f"Minimum: {min_S:.12f}")
print(f"Maximum: {max_S:.12f}")
print(f"Range: {max_S - min_S:.2e}")
print("-" * 80)
print(f"CODATA 2022: {float(codata_2022):.12f}")
print(f"Difference: {mean_S - float(codata_2022):.2e}")
print(f"Relative error: {abs(mean_S - float(codata_2022)) / float(codata_2022):.2e}")
print("-" * 80)

# =================================================================================
# VERDICT
# =================================================================================
abs_diff = abs(mean_S - float(codata_2022))
if abs_diff < 1e-8:
    verdict = "✅ GREEN - Model verified"
    verdict_detail = f"Difference {abs_diff:.2e} < 1e-8"
elif abs_diff < 1e-6:
    verdict = "🟡 YELLOW - Acceptable, check convergence"
    verdict_detail = f"Difference {abs_diff:.2e} between 1e-8 and 1e-6"
else:
    verdict = "🔴 RED - Model fails"
    verdict_detail = f"Difference {abs_diff:.2e} > 1e-6"

print()
print("=" * 80)
print("VERDICT")
print("=" * 80)
print(f"Status: {verdict}")
print(f"Reason: {verdict_detail}")
print()

# =================================================================================
# BOUNDARY CHECK (Seal 1: q ≤ 45)
# =================================================================================
n_check = 10000
boundary_samples = [np.random.choice(q_space, p=probabilities) for _ in range(n_check)]
max_q_observed = max(boundary_samples)
if max_q_observed <= max_q:
    print(f"✅ Boundary check: q ≤ {max_q} respected (max observed = {max_q_observed})")
else:
    print(f"⚠️ Boundary violation: q = {max_q_observed} observed (exceeds limit {max_q})")

# =================================================================================
# RUNNING MEAN STABILITY (Ergodic convergence - Seal 2)
# =================================================================================
running_means = np.cumsum(S_array) / np.arange(1, n_iterations + 1)
running_std = np.std(running_means[-1000:])
print(f"Running mean stability (last 1000 values std): {running_std:.2e}")

# =================================================================================
# DISTRIBUTION CHECK - Verify P(q) matches expected exponential decay
# =================================================================================
freq = Counter(boundary_samples)
expected_prob = {q: probabilities[q-1] for q in range(1, max_q + 1)}
print()
print("=" * 80)
print("DISTRIBUTION CHECK (first 10 quotients)")
print("=" * 80)
print(f"{'q':<6} {'Observed %':<12} {'Expected %':<12} {'Deviation':<12}")
print("-" * 45)
for q in range(1, 11):
    obs_pct = 100 * freq.get(q, 0) / n_check
    exp_pct = 100 * expected_prob[q]
    dev = obs_pct - exp_pct
    print(f"{q:<6} {obs_pct:<12.2f} {exp_pct:<12.2f} {dev:<+12.2f}")

# =================================================================================
# GRAPHICS SECTION
# =================================================================================
print()
print("=" * 80)
print("GENERATING GRAPHICS")
print("=" * 80)

plt.style.use('seaborn-v0_8-whitegrid')
fig = plt.figure(figsize=(14, 10))

# 1) Histogram of measured S values
ax1 = fig.add_subplot(2, 2, 1)
ax1.hist(S_values, bins=100, color='skyblue', edgecolor='black', alpha=0.7)
ax1.axvline(float(codata_2022), color='red', linestyle='--', linewidth=2,
            label=f'CODATA 2022 = {float(codata_2022):.9f}')
ax1.axvline(mean_S, color='blue', linestyle='-', linewidth=2,
            label=f'Mean = {mean_S:.9f}')
ax1.set_xlabel(r'$\langle S \rangle$ (predicted $\alpha^{-1}$)')
ax1.set_ylabel('Frequency')
ax1.set_title(f'Distribution of {n_iterations:,} measurements')
ax1.legend()

# 2) Running mean convergence
ax2 = fig.add_subplot(2, 2, 2)
running_means_full = np.cumsum(S_array) / np.arange(1, n_iterations + 1)
ax2.plot(running_means_full, linewidth=0.5, color='steelblue')
ax2.axhline(float(codata_2022), color='red', linestyle='--', linewidth=1.5,
            label='CODATA 2022')
ax2.axhline(mean_S, color='blue', linestyle='-', linewidth=1.5,
            label=f'Final mean = {mean_S:.9f}')
ax2.set_xlabel('Iteration')
ax2.set_ylabel('Running mean')
ax2.set_title('Ergodic convergence')
ax2.legend()
ax2.set_xscale('log')

# 3) Distribution of quotients (first 20 positions as proxy)
ax3 = fig.add_subplot(2, 2, 3)
all_q = [q for seq in all_sequences[:10000] for q in seq]  # Sample 10k sequences
counter_q = Counter(all_q)
x_vals = sorted(counter_q.keys())[:20]
y_vals = [counter_q[x] / len(all_q) * 100 for x in x_vals]
ax3.bar(x_vals, y_vals, color='lightgreen', edgecolor='black', alpha=0.7)
ax3.set_xlabel('Quotient q')
ax3.set_ylabel('Probability (%)')
ax3.set_title('Distribution of quotients (first 20 values)')
ax3.set_xticks(x_vals)

# 4) Correlation heatmap among first 4 quotients
ax4 = fig.add_subplot(2, 2, 4)
first4 = np.array([seq[:4] for seq in all_sequences[:10000]])
corr_matrix = np.corrcoef(first4.T)
im = ax4.imshow(corr_matrix, cmap='coolwarm', vmin=-1, vmax=1)
ax4.set_xticks(range(4))
ax4.set_yticks(range(4))
ax4.set_xticklabels([f'q{i+1}' for i in range(4)])
ax4.set_yticklabels([f'q{i+1}' for i in range(4)])
ax4.set_title('Correlation among first 4 quotients')
plt.colorbar(im, ax=ax4)

plt.tight_layout()
plt.show()

print()
print("=" * 80)
print("VERIFICATION COMPLETE")
print("=" * 80)